/**
 * Prototype data for the Editorial & Partnership Dashboard.
 *
 * Published records are derived from the live public content graph so the
 * three surfaces stay one system: nothing here duplicates a public record,
 * it wraps it with editorial workflow state.
 */

import {
  collections,
  events,
  forms,
  papers,
  people,
  places,
  stories,
} from "@/data/content";
import { institutions } from "@/data/institutions";
import { collaborations } from "@/data/collaborations";
import {
  emptyRelationships,
  type ActivityEntry,
  type AdminNotification,
  type AdminUser,
  type Claim,
  type ContentItem,
  type ContentKind,
  type CurationSlot,
  type FollowUp,
  type Inquiry,
  type Interaction,
  type MediaAsset,
  type FocusOverride,
  type Partner,
  type PipelineCollaboration,
  type Relationships,
  type SourceRecord,
  type TaxonomyTerm,
} from "./types";

const DAY = 86_400_000;
export const at = (offsetDays: number, hour = 10) => {
  const d = new Date(Date.now() + offsetDays * DAY);
  d.setHours(hour, offsetDays % 2 ? 42 : 18, 0, 0);
  return d.toISOString();
};

/* ---------------- team ---------------- */

export const seedUsers: AdminUser[] = [
  { id: "u-maya", name: "Maya Rahardjo", email: "maya@indonesiavibes.org", role: "Managing Editor", focus: "Editorial priorities, approval and scheduling", active: true },
  { id: "u-arif", name: "Arif Santoso", email: "arif@indonesiavibes.org", role: "Content Editor", focus: "Cultural subjects and long-form stories", active: true },
  { id: "u-nur", name: "Nur Aisyah", email: "nur@indonesiavibes.org", role: "Researcher / Fact Checker", focus: "Sources, claims and archival verification", active: true },
  { id: "u-pak-w", name: "Wayan Sudarma", email: "wayan@indonesiavibes.org", role: "Subject Reviewer", focus: "Performing arts and ritual context", active: true },
  { id: "u-claire", name: "Claire Whitfield", email: "claire@indonesiavibes.org", role: "English Editor", focus: "International readability and terminology", active: true },
  { id: "u-tomas", name: "Tomás Ferreira", email: "tomas@indonesiavibes.org", role: "Multimedia Editor", focus: "Photography, rights and alt text", active: true },
  { id: "u-siti", name: "Siti Hapsari", email: "siti@indonesiavibes.org", role: "Partnership Officer", focus: "Inquiries, introductions and collaborations", active: true },
  { id: "u-dewi", name: "Dewi Larasati", email: "dewi@indonesiavibes.org", role: "Super Admin", focus: "Platform configuration and taxonomy", active: true },
  { id: "u-board", name: "Rudi Hartono", email: "rudi@indonesiavibes.org", role: "Viewer / Leadership", focus: "Programme oversight", active: true },
];

/* ---------------- derived published content ---------------- */

const rel = (partial: Partial<Relationships>): Relationships => ({ ...emptyRelationships(), ...partial });

let n = 0;
const nextId = (prefix: string) => `${prefix}-${++n}`;

const reviewDates = (publishedOffset: number, frequency: number) => ({
  publishedAt: at(publishedOffset),
  lastReviewed: at(publishedOffset + Math.round(frequency / 3)),
  nextReview: at(publishedOffset + frequency),
  reviewFrequencyDays: frequency,
});

function published(
  kind: ContentKind,
  source: { id: string; slug?: string },
  title: string,
  opts: {
    path: string;
    themes?: string[];
    countries?: string[];
    location?: string;
    editor: string;
    offset: number;
    frequency: number;
    fields: Record<string, string>;
    relationships?: Partial<Relationships>;
    deliveryType?: ContentItem["deliveryType"];
    contentSource?: ContentItem["contentSource"];
    topics?: string[];
    sourceAttribution?: string;
  },
): ContentItem {
  return {
    id: `c-${source.id}`,
    kind,
    ...(opts.deliveryType ? { deliveryType: opts.deliveryType } : {}),
    ...(opts.contentSource ? { contentSource: opts.contentSource } : {}),
    ...(opts.topics ? { topics: opts.topics } : {}),
    ...(opts.sourceAttribution ? { sourceAttribution: opts.sourceAttribution } : {}),
    title,
    ...(source.slug ? { slug: source.slug } : {}),
    publicPath: opts.path,
    status: "published",
    priority: "Normal",
    assignedTo: opts.editor,
    themes: opts.themes ?? [],
    countries: opts.countries ?? ["Indonesia"],
    ...(opts.location ? { location: opts.location } : {}),
    createdAt: at(opts.offset - 30),
    updatedAt: at(opts.offset + 2),
    stageSince: at(opts.offset),
    ...reviewDates(opts.offset, opts.frequency),
    fields: opts.fields,
    relationships: rel(opts.relationships ?? {}),
    culturalReview: { flags: [], decision: "No concern", reviewer: "Wayan Sudarma", date: at(opts.offset - 4) },
    languageReview: { complete: true, reviewer: "Claire Whitfield", date: at(opts.offset - 3) },
    feedback: [],
    notes: [],
    versions: [
      { id: nextId("v"), label: "v1", editor: opts.editor, date: at(opts.offset - 20), summary: "First editorial pass from the contributor draft." },
      { id: nextId("v"), label: "v2", editor: "Claire Whitfield", date: at(opts.offset - 3), summary: "Language review: terminology and geographic references." },
      { id: nextId("v"), label: "v3", editor: opts.editor, date: at(opts.offset), summary: "Published." },
    ],
    prototype: true,
  };
}

const editors = ["Arif Santoso", "Maya Rahardjo", "Arif Santoso", "Nur Aisyah"];
const pickEditor = (i: number) => editors[i % editors.length]!;

const storyItems: ContentItem[] = stories.map((s, i) =>
  published("story", s, s.title, {
    path: `/stories/${s.slug}`,
    themes: s.topics ?? [],
    ...(s.deliveryType ? { deliveryType: s.deliveryType } : {}),
    ...(s.contentSource ? { contentSource: s.contentSource } : {}),
    ...(s.topics ? { topics: s.topics } : {}),
    ...(s.sourceAttribution ? { sourceAttribution: s.sourceAttribution } : {}),
    countries: ["Indonesia"],
    editor: pickEditor(i),
    offset: -40 - i * 9,
    frequency: 365,
    fields: {
      title: s.title,
      standfirst: s.dek,
      storyType: s.kind,
      author: s.author ?? "Indonesia Vibes editorial team",
      narrative: (s.body ?? []).slice(0, 2).join("\n\n"),
      cta: "Explore the related cultural subject",
    },
    relationships: {
      culture: s.formIds ?? [],
      people: s.peopleIds ?? [],
      places: s.placeIds ?? [],
      research: [],
    },
  }),
);

const cultureItems: ContentItem[] = forms.map((f, i) =>
  published("culture", f, f.name, {
    path: `/culture/${f.slug}`,
    themes: [f.pillar],
    editor: pickEditor(i + 1),
    offset: -120 - i * 6,
    frequency: 540,
    fields: {
      englishName: f.name,
      originalName: (f.aliases ?? [])[0] ?? f.name,
      pronunciation: "",
      introduction: f.summary ?? "",
      whyItMatters: f.whyMatters ?? "",
      historicalContext: f.whatItIs ?? "",
      contemporaryPractice: f.today ?? "",
      geography: f.practisedIn ?? "",
      sensitivity: f.sensitivity ?? "",
      recognition: f.unesco ?? "",
    },
    relationships: {
      people: [],
      places: [f.originPlaceId],
      research: [],
    },
  }),
);

const peopleItems: ContentItem[] = people.map((p, i) =>
  published(p.entity === "community" ? "community" : "person", p, p.name, {
    path: `/people/${p.slug}`,
    themes: p.themes ?? [],
    editor: pickEditor(i + 2),
    offset: -80 - i * 5,
    frequency: 270,
    fields: {
      name: p.name,
      role: p.role ?? "",
      based: p.based ?? "",
      biography: p.bio,
      expertise: (p.expertise ?? []).join(", "),
      consent: "Profile reviewed with the subject before publication.",
    },
    relationships: { culture: p.formIds ?? [], places: p.placeId ? [p.placeId] : [], institutions: p.institutionIds ?? [] },
  }),
);

const placeItems: ContentItem[] = places
  .filter((p) => p.country === "Indonesia")
  .map((p, i) =>
    published("place", p, p.name, {
      path: `/places/${p.slug}`,
      themes: p.themes ?? [],
      location: `${p.city}, ${p.country}`,
      editor: pickEditor(i + 3),
      // Visitor information ages faster, so the review cycle is short.
      offset: -200 - i * 8,
      frequency: 180,
      fields: {
        name: p.name,
        type: p.type ?? "",
        summary: p.summary ?? "",
        significance: (p.significance ?? [])[0] ?? "",
        visiting: p.visiting?.guidance ?? "",
        coordinates: `${p.lat}, ${p.lng}`,
      },
      relationships: { culture: [], places: [] },
    }),
  );

const eventItems: ContentItem[] = events.map((e, i) =>
  published("event", e, e.title, {
    path: `/events/${e.slug}`,
    themes: [],
    countries: ["Indonesia"],
    location: e.venue ?? "",
    editor: "Maya Rahardjo",
    offset: -30 - i * 3,
    frequency: 30,
    fields: {
      title: e.title,
      type: e.type ?? "",
      summary: e.summary ?? "",
      dates: `${e.startDate} – ${e.endDate}`,
      venue: e.venue ?? "",
      timeZone: e.timeZone ?? "",
      format: "In person",
      officialLink: "",
      admission: e.admission ?? "",
    },
    relationships: { culture: e.formIds ?? [], people: e.peopleIds ?? [], institutions: e.institutionIds ?? [] },
  }),
);

const collaborationItems: ContentItem[] = collaborations.map((c, i) =>
  published("collaboration", c, c.title, {
    path: `/collaborations/${c.slug}`,
    themes: c.themes ?? [],
    countries: c.countries ?? [],
    editor: "Siti Hapsari",
    offset: -150 - i * 12,
    frequency: 365,
    fields: {
      title: c.title,
      countries: (c.countries ?? []).join(", "),
      intro: c.intro,
      objectives: (c.objectives ?? []).join("; "),
      activities: (c.activities ?? []).join("\n"),
    },
    relationships: { institutions: c.indonesianPartnerIds ?? [], people: c.peopleIds ?? [], places: c.placeIds ?? [] },
  }),
);

const collectionItems: ContentItem[] = collections.map((c, i) =>
  published("collection", c, c.title, {
    path: `/collections/${c.slug}`,
    themes: [],
    editor: "Maya Rahardjo",
    offset: -90 - i * 15,
    frequency: 365,
    fields: {
      title: c.title,
      standfirst: c.dek,
      theme: "",
      statement: c.dek,
      editor: "Maya Rahardjo",
    },
    relationships: { culture: c.formIds ?? [] },
  }),
);

const institutionItems: ContentItem[] = institutions.map((inst, i) =>
  published("institution", inst, inst.name, {
    path: `/institutions/${inst.slug}`,
    themes: inst.themes ?? [],
    countries: [inst.country],
    location: `${inst.city}, ${inst.country}`,
    editor: "Arif Santoso",
    offset: -260 - i * 7,
    frequency: 270,
    fields: {
      name: inst.name,
      type: inst.type,
      profile: inst.profile,
      expertise: (inst.expertise ?? []).join(", "),
      programmes: (inst.programmes ?? []).join("; "),
      website: inst.website ?? "",
    },
    relationships: { people: inst.peopleIds ?? [], places: inst.placeId ? [inst.placeId] : [] },
  }),
);

/* ---------------- in-flight editorial work ---------------- */

const inFlight: ContentItem[] = [
  {
    id: "c-sub-gamelan",
    kind: "story",
    title: "Gamelan Across Oceans",
    status: "ready_for_approval",
    priority: "High",
    assignedTo: "Arif Santoso",
    contributor: "Maya Kusuma",
    organisation: "Embassy of the Republic of Indonesia, Lisbon",
    submissionId: "proto-gamelan",
    themes: ["Music", "Performing Arts"],
    countries: ["Indonesia", "United Kingdom"],
    location: "London, United Kingdom",
    createdAt: at(-26),
    updatedAt: at(-1),
    stageSince: at(-2),
    fields: {
      title: "Gamelan Across Oceans",
      standfirst:
        "How a Javanese ensemble tuning travelled with students, then stayed — and what British players changed when it arrived.",
      storyType: "Feature",
      author: "Maya Kusuma with the Indonesia Vibes editorial team",
      narrative:
        "The first sets arrived as diplomatic gifts and ended up in university basements. Forty years later they are booked solid.\n\nWhat happened in between is not a story about export. It is a story about who was allowed to teach.",
      cta: "Explore Gamelan as a cultural subject",
    },
    relationships: rel({
      culture: ["cf-gamelan"],
      people: ["pe-2", "pe-c2"],
      places: ["pl-yogya", "pl-london"],
      institutions: ["in-sound-archive", "in-mission-london"],
      collaborations: ["cl-uk-music"],
      research: ["rp-4"],
    }),
    culturalReview: {
      flags: ["Ceremonial practice"],
      decision: "Context required",
      reviewer: "Wayan Sudarma",
      context:
        "Court repertoire referenced in section three is performed on a fixed ritual calendar. Keep the framing descriptive and avoid implying the pieces are freely programmable.",
      date: at(-5),
    },
    subjectReview: {
      reviewer: "Wayan Sudarma",
      outcome: "Substance approved",
      comment: "Accurate on tuning practice. Added a note on ceremonial repertoire.",
      date: at(-5),
      questions: ["Is the ensemble described as court-trained or independent?"],
    },
    languageReview: { complete: true, reviewer: "Claire Whitfield", date: at(-3), notes: "Removed two untranslated terms." },
    feedback: [
      {
        id: "fb-1",
        section: "Historical Context",
        note: "Please provide a source for the statement about the first instrument sets arriving in 1978.",
        kind: "Required",
        visibleToContributor: true,
        author: "Nur Aisyah",
        date: at(-9),
        resolved: true,
      },
    ],
    notes: [
      { id: "nt-1", kind: "Private note", body: "Hold until the mission confirms the photographer credit — not a contributor-facing issue.", author: "Tomás Ferreira", date: at(-4) },
      { id: "nt-2", kind: "Comment", body: "@Maya this is ready from my side.", author: "Arif Santoso", date: at(-2), mentions: ["Maya Rahardjo"] },
    ],
    versions: [
      { id: "vg-1", label: "v1", editor: "Arif Santoso", date: at(-24), summary: "Structure pass, split the history section." },
      { id: "vg-2", label: "v2", editor: "Nur Aisyah", date: at(-9), summary: "Two claims flagged for sources." },
      { id: "vg-3", label: "v3", editor: "Claire Whitfield", date: at(-3), summary: "Language review complete." },
    ],
    prototype: true,
  },
  {
    id: "c-sub-tokyo-film",
    kind: "event",
    title: "Indonesian Film Programme in Tokyo",
    status: "revision_requested",
    priority: "High",
    assignedTo: "Maya Rahardjo",
    contributor: "Rui Tavares",
    organisation: "Embassy of the Republic of Indonesia, Lisbon",
    submissionId: "proto-tokyo",
    themes: ["Film"],
    countries: ["Japan"],
    location: "Tokyo, Japan",
    createdAt: at(-14),
    updatedAt: at(-3),
    stageSince: at(-3),
    fields: {
      title: "Indonesian Film Programme in Tokyo",
      type: "Screening season",
      summary: "A six-film season of contemporary Indonesian cinema with director conversations.",
      dates: `${at(12).slice(0, 10)} – ${at(19).slice(0, 10)}`,
      venue: "Shibuya screening rooms",
      timeZone: "",
      format: "In person",
      officialLink: "",
      admission: "Ticketed",
    },
    relationships: rel({ culture: ["cf-cinema"], people: ["pe-3"], institutions: ["in-screen-festival"], collaborations: ["cl-jp-film"] }),
    culturalReview: { flags: [] },
    languageReview: { complete: false },
    feedback: [
      { id: "fb-2", section: "Official source", note: "We need a public link on the venue or festival site before this can be listed.", kind: "Required", visibleToContributor: true, author: "Maya Rahardjo", date: at(-3) },
      { id: "fb-3", section: "Dates and time zone", note: "Please confirm the time zone so the event shows correctly for international readers.", kind: "Required", visibleToContributor: true, author: "Maya Rahardjo", date: at(-3) },
    ],
    notes: [],
    versions: [{ id: "vt-1", label: "v1", editor: "Maya Rahardjo", date: at(-4), summary: "Initial screening." }],
    prototype: true,
  },
  {
    id: "c-sub-textile",
    kind: "collection",
    title: "Living Textile Traditions",
    status: "editorial_review",
    priority: "Normal",
    assignedTo: "Arif Santoso",
    contributor: "Dewi Anggraini",
    organisation: "Nusantara Textile Museum",
    submissionId: "proto-textile",
    themes: ["Craft & Design", "Heritage"],
    countries: ["Indonesia"],
    createdAt: at(-11),
    updatedAt: at(-1),
    stageSince: at(-6),
    fields: {
      title: "Living Textile Traditions",
      standfirst: "Dye gardens, apprenticeships and the households that decide what leaves the village.",
      theme: "Craft & Design",
      statement: "A collection that follows cloth backwards: from the gallery wall to the plot of morinda behind the loom.",
      editor: "Arif Santoso",
    },
    relationships: rel({ culture: ["cf-ikat"], people: ["pe-1", "pe-c1"], places: ["pl-sumba", "pl-kaliuda"], institutions: ["in-textile-museum"], research: ["rp-2"] }),
    culturalReview: { flags: ["Community-owned knowledge"], decision: "Permission required", reviewer: "Wayan Sudarma", context: "Motif photographs need the weaving house's written agreement before publication.", date: at(-4) },
    languageReview: { complete: false },
    feedback: [
      { id: "fb-4", section: "Collection statement", note: "Can we open on a specific household rather than the museum?", kind: "Suggestion", visibleToContributor: true, author: "Arif Santoso", date: at(-2) },
    ],
    notes: [{ id: "nt-3", kind: "Private note", body: "Museum contact is slow over the holiday period — plan around it.", author: "Arif Santoso", date: at(-2) }],
    versions: [{ id: "vx-1", label: "v1", editor: "Arif Santoso", date: at(-6), summary: "Sequence proposed." }],
    prototype: true,
  },

  {
    id: "c-sub-maritime",
    kind: "story",
    title: "Reading the Sea",
    status: "subject_review",
    priority: "Normal",
    assignedTo: "Wayan Sudarma",
    contributor: "Rui Tavares",
    organisation: "Maritime Knowledge Centre",
    themes: ["Heritage", "Indigenous Knowledge"],
    countries: ["Indonesia", "Portugal"],
    createdAt: at(-19),
    updatedAt: at(-2),
    stageSince: at(-5),
    fields: {
      title: "Reading the Sea",
      standfirst: "Konjo navigation without instruments, and the archives that only half recorded it.",
      storyType: "Feature",
      author: "Rui Tavares",
      narrative: "Wind, swell and the colour of water were the instruments. The written record starts three centuries late.",
      cta: "Read the maritime heritage collaboration",
    },
    relationships: rel({ culture: ["cf-phinisi"], people: ["pe-c3"], places: ["pl-bira"], institutions: ["in-maritime-centre"], collaborations: ["cl-pt-maritime"], research: ["rp-1"] }),
    culturalReview: { flags: ["Restricted knowledge"], decision: "Limit public detail", reviewer: "Wayan Sudarma", context: "Certain sailing prayers are not for publication. Summarise their function without transcribing them.", date: at(-5) },
    languageReview: { complete: false },
    feedback: [],
    notes: [],
    versions: [{ id: "vm-1", label: "v1", editor: "Arif Santoso", date: at(-12), summary: "Structure pass." }],
    prototype: true,
  },
  {
    id: "c-sub-kitchens",
    kind: "story",
    title: "Diaspora kitchens in Porto",
    status: "submitted",
    priority: "Normal",
    contributor: "Dewi Anggraini",
    organisation: "Embassy of the Republic of Indonesia, Lisbon",
    submissionId: "proto-kitchens",
    themes: ["Culinary Culture"],
    countries: ["Portugal"],
    createdAt: at(-2),
    updatedAt: at(-2),
    stageSince: at(-2),
    fields: {
      title: "Diaspora kitchens in Porto",
      standfirst: "Six households, one spice cupboard, and a Sunday that has run for eleven years.",
      storyType: "Dispatch",
      author: "Dewi Anggraini",
      narrative: "The cooking rota is older than the association that now hosts it.",
      cta: "",
    },
    relationships: rel({ culture: ["cf-spice"], places: ["pl-lisbon"] }),
    culturalReview: { flags: ["Personal information"] },
    languageReview: { complete: false },
    feedback: [],
    notes: [],
    versions: [],
    prototype: true,
  },
  {
    id: "c-sub-cinema-subject",
    kind: "culture",
    title: "Contemporary Indonesian Cinema",
    status: "english_editing",
    priority: "Normal",
    assignedTo: "Claire Whitfield",
    contributor: "Jakarta Screen Festival",
    organisation: "Jakarta Screen Festival",
    themes: ["Film", "Contemporary Culture"],
    countries: ["Indonesia"],
    createdAt: at(-22),
    updatedAt: at(-1),
    stageSince: at(-3),
    fields: {
      englishName: "Contemporary Indonesian Cinema",
      originalName: "Sinema Indonesia kontemporer",
      pronunciation: "si-NE-ma",
      introduction: "A domestic-first film culture with one of the fastest growing box offices in Asia.",
      whyItMatters: "Audiences at home set the agenda before festivals abroad do.",
      historicalContext: "Post-1998 deregulation reopened production outside the state studios.",
      contemporaryPractice: "Independent producers now finance from streaming presales and regional co-production.",
      geography: "Jakarta, Yogyakarta, Bandung",
      sensitivity: "",
      recognition: "",
    },
    relationships: rel({ culture: [], people: ["pe-3"], places: ["pl-jakarta"], institutions: ["in-screen-festival"], events: ["ev-3"], research: ["rp-5"] }),
    culturalReview: { flags: [], decision: "No concern", reviewer: "Wayan Sudarma", date: at(-6) },
    languageReview: { complete: false, notes: "Check 'sinetron' — needs a short gloss for international readers." },
    feedback: [],
    notes: [],
    versions: [],
    prototype: true,
  },
  {
    id: "c-sub-museum-profile",
    kind: "institution",
    title: "Museu Nacional de Arte Antiga — partner profile",
    status: "initial_review",
    priority: "Low",
    contributor: "Maya Kusuma",
    organisation: "Embassy of the Republic of Indonesia, Lisbon",
    themes: ["Heritage"],
    countries: ["Portugal"],
    location: "Lisbon, Portugal",
    createdAt: at(-4),
    updatedAt: at(-4),
    stageSince: at(-4),
    fields: {
      name: "Museu Nacional de Arte Antiga",
      type: "Museum",
      profile: "Holds Portuguese collections with substantial Asian maritime trade material.",
      expertise: "Maritime trade history, conservation",
      programmes: "Exhibition partnerships, conservation exchange",
      website: "https://example.pt/mnaa",
    },
    relationships: rel({ places: ["pl-lisbon"], collaborations: ["cl-pt-maritime"] }),
    culturalReview: { flags: [] },
    languageReview: { complete: false },
    feedback: [],
    notes: [],
    versions: [],
    prototype: true,
  },
  {
    id: "c-sub-batik-media",
    kind: "culture",
    title: "Batik pesisir",
    status: "media_rights",
    priority: "Normal",
    assignedTo: "Tomás Ferreira",
    contributor: "Nusantara Textile Museum",
    organisation: "Nusantara Textile Museum",
    themes: ["Craft & Design", "Heritage"],
    countries: ["Indonesia"],
    createdAt: at(-30),
    updatedAt: at(-1),
    stageSince: at(-2),
    fields: {
      englishName: "Coastal batik",
      originalName: "Batik pesisir",
      pronunciation: "BA-tik pe-SI-sir",
      introduction: "North-coast batik, where Chinese, Arab, Javanese and Dutch motifs share a single cloth.",
      whyItMatters: "It records trade contact more precisely than most written sources of the same period.",
      historicalContext: "Workshops in Pekalongan and Lasem served export markets from the nineteenth century.",
      contemporaryPractice: "Family workshops still hand-draw, with natural dye lines returning since 2015.",
      geography: "Pekalongan, Lasem, Cirebon",
      sensitivity: "",
      recognition: "UNESCO Intangible Cultural Heritage (batik, 2009)",
    },
    relationships: rel({ people: ["pe-1"], places: ["pl-jakarta"], institutions: ["in-textile-museum"] }),
    culturalReview: { flags: [], decision: "No concern", reviewer: "Wayan Sudarma", date: at(-8) },
    languageReview: { complete: true, reviewer: "Claire Whitfield", date: at(-4) },
    feedback: [],
    notes: [],
    versions: [],
    prototype: true,
  },
  {
    id: "c-sub-sumba-scheduled",
    kind: "event",
    title: "Sumba Weaving Week open studios",
    status: "scheduled",
    priority: "Normal",
    assignedTo: "Maya Rahardjo",
    contributor: "Kaliuda Weaving House",
    organisation: "Kaliuda Weaving House",
    themes: ["Craft & Design"],
    countries: ["Indonesia"],
    location: "Pahunga Lodu, Indonesia",
    createdAt: at(-16),
    updatedAt: at(-1),
    stageSince: at(-1),
    scheduledFor: at(3, 9),
    scheduleTimeZone: "Asia/Makassar (WITA)",
    fields: {
      title: "Sumba Weaving Week open studios",
      type: "Open studio",
      summary: "Twelve weaving houses open their dye gardens and looms for a week.",
      dates: `${at(21).slice(0, 10)} – ${at(28).slice(0, 10)}`,
      venue: "Kaliuda and neighbouring villages",
      timeZone: "Asia/Makassar (WITA)",
      format: "In person",
      officialLink: "https://indonesia.travel",
      admission: "Free, hosted visits",
    },
    relationships: rel({ culture: ["cf-ikat"], people: ["pe-1", "pe-c1"], places: ["pl-kaliuda", "pl-sumba"], institutions: ["in-kaliuda"] }),
    culturalReview: { flags: ["Community-owned knowledge"], decision: "Context required", reviewer: "Wayan Sudarma", context: "State clearly that visits are hosted, not ticketed.", date: at(-6) },
    languageReview: { complete: true, reviewer: "Claire Whitfield", date: at(-3) },
    feedback: [],
    notes: [],
    versions: [],
    featured: ["In Focus"],
    prototype: true,
  },
];

export const seedContent: ContentItem[] = [
  ...inFlight,
  ...storyItems,
  ...cultureItems,
  ...peopleItems,
  ...placeItems,
  ...eventItems,
  ...collaborationItems,
  ...collectionItems,
  ...institutionItems,
];

/* ---------------- sources, claims, media ---------------- */

export const seedSources: SourceRecord[] = [
  { id: "src-1", contentId: "c-sub-gamelan", title: "Instrument sets in British universities, 1978–1994", author: "J. Mercer", publisher: "Journal of Ethnomusicology", year: "2019", url: "https://example.org/mercer-1978", type: "Academic publication", status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-8) },
  { id: "src-2", contentId: "c-sub-gamelan", title: "Cultural mission correspondence, London", author: "Indonesian Cultural Mission", publisher: "Mission archive", year: "1981", type: "Archive", owner: "Indonesian Cultural Mission, London", status: "Verification in progress", notes: "Awaiting a scan of the accession note." },
  { id: "src-3", contentId: "c-sub-maritime", title: "Proportional rule systems in Konjo hull construction", author: "Maritime Knowledge Centre", year: "2024", type: "Academic publication", status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-11) },
  { id: "src-4", contentId: "c-sub-maritime", title: "Interview with master builder, Tanjung Bira", type: "Interview", owner: "Bira Boatwrights", year: "2025", status: "Needs clarification", notes: "Consent recorded verbally; written confirmation requested." },
  { id: "src-5", contentId: "c-sub-textile", title: "Morinda dye chemistry and the two-year hinggi", author: "Nusantara Textile Museum", year: "2025", type: "Institutional source", status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-5) },
  { id: "src-6", contentId: "c-sub-residency", title: "Residency call, host institution page", url: "https://example.pt/residency", type: "Official source", year: "2026", status: "Verification in progress", notes: "Deadline on the page differs from the submission by two days." },
  { id: "src-7", contentId: "c-sub-tokyo-film", title: "Festival programme announcement", type: "Official source", status: "Unverified", notes: "No public link supplied yet." },
  { id: "src-8", contentId: "c-sub-cinema-subject", title: "Register loss in Indonesian screen translation", author: "R. Kusuma", year: "2025", type: "Academic publication", status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-14) },
  { id: "src-9", contentId: "c-sub-batik-media", title: "UNESCO Intangible Cultural Heritage listing: batik", url: "https://ich.unesco.org", type: "Official source", year: "2009", status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-20) },
  { id: "src-10", contentId: "c-sub-kitchens", title: "Association records, Porto", type: "Community source", status: "Unverified" },
];

export const seedClaims: Claim[] = [
  { id: "cl-1", contentId: "c-sub-gamelan", section: "Historical context", text: "The first complete instrument sets reached British universities in 1978.", sourceIds: ["src-1"], status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-8) },
  { id: "cl-2", contentId: "c-sub-gamelan", section: "Contemporary practice", text: "Ensembles now rehearse weekly in at least fourteen UK institutions.", sourceIds: [], status: "Requires source", notes: "Contributor asked for a current list." },
  { id: "cl-3", contentId: "c-sub-maritime", section: "Historical context", text: "Hulls are built before frames, reversing European sequence.", sourceIds: ["src-3"], status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-11) },
  { id: "cl-4", contentId: "c-sub-maritime", section: "Navigation", text: "Practised across several regions since at least the sixteenth century.", sourceIds: ["src-4"], status: "Source attached", notes: "Interview source needs written consent before this stands." },
  { id: "cl-5", contentId: "c-sub-cinema-subject", section: "Contemporary practice", text: "Domestic admissions have grown every year since 2016 apart from 2020.", sourceIds: [], status: "Requires source" },
  { id: "cl-6", contentId: "c-sub-textile", section: "Collection statement", text: "A hinggi can take two years of dye time.", sourceIds: ["src-5"], status: "Verified", verifiedBy: "Nur Aisyah", verifiedAt: at(-5) },
];

const media = (
  id: string,
  contentId: string,
  fileName: string,
  caption: string,
  creator: string,
  permission: MediaAsset["permission"],
  extra: Partial<MediaAsset> = {},
): MediaAsset => ({
  id,
  contentId,
  kind: "Image",
  fileName,
  caption,
  creator,
  credit: creator,
  rightsHolder: extra.rightsHolder ?? creator,
  permission,
  altText: extra.altText ?? caption,
  required: extra.required ?? true,
  updatedAt: at(-3),
  ...extra,
});

export const seedMedia: MediaAsset[] = [
  media("md-1", "c-sub-gamelan", "gamelan-rehearsal-01.jpg", "Rehearsal at a university gamelan room in London.", "Sarah Lindqvist", "Permission received"),
  media("md-2", "c-sub-gamelan", "gamelan-instruments-02.jpg", "Bronze keys laid out before tuning.", "Unknown mission archive", "Needs confirmation", { rightsHolder: "Indonesian Cultural Mission, London", restrictions: "Archive copy; provenance unclear." }),
  media("md-3", "c-sub-textile", "kaliuda-dye-garden.jpg", "Morinda roots drying behind the weaving house.", "Rambu Ana Hàmu", "Permission received", { rightsHolder: "Kaliuda Weaving House" }),
  media("md-4", "c-sub-textile", "hinggi-motif-detail.jpg", "Detail of a clan motif on an unfinished hinggi.", "Nusantara Textile Museum", "Restricted", { restrictions: "Motif photography requires the weaving house's written agreement." }),
  media("md-5", "c-sub-maritime", "bira-hull.jpg", "A phinisi hull under construction on the beach at Bira.", "Hendra Mulyadi", "Licensed"),
  media("md-6", "c-sub-tokyo-film", "tokyo-programme-poster.jpg", "Season poster supplied by the organiser.", "Unknown", "Unknown", { restrictions: "No creator supplied." }),
  media("md-7", "c-sub-batik-media", "batik-pesisir-01.jpg", "Hand-drawn coastal batik in a Pekalongan workshop.", "Ratih Kusuma", "Permission received"),
  media("md-8", "c-sub-batik-media", "batik-pesisir-02.jpg", "Indigo vat, north coast workshop.", "Ratih Kusuma", "Needs confirmation", { restrictions: "Model release for the two workers is missing." }),
  media("md-9", "c-sub-cinema-subject", "screening-audience.jpg", "Audience at a Jakarta premiere.", "Nadia Suryani", "Permission received", { required: false }),
  media("md-10", "c-sub-sumba-scheduled", "open-studio.jpg", "Open studio week, Kaliuda.", "Kaliuda Weaving House", "Permission received"),
  media("md-11", "c-sub-kitchens", "porto-kitchen.jpg", "Sunday cooking rota, Porto.", "Dewi Anggraini", "Needs confirmation", { restrictions: "Household consent recorded verbally only." }),
  { ...media("md-12", "c-sub-maritime", "sailing-prayer.wav", "Recording referenced in the navigation section.", "Maritime Knowledge Centre", "Do not publish", { restrictions: "Community asked that the recording is not published." }), kind: "Audio" },
];

/* ---------------- partners ---------------- */

export const seedPartners: Partner[] = [
  {
    id: "pa-mnaa",
    name: "Museu Nacional de Arte Antiga",
    type: "Museum",
    country: "Portugal",
    city: "Lisbon",
    themes: ["Heritage"],
    expertise: ["Maritime trade history", "Conservation"],
    collaborationInterests: ["Joint exhibitions", "Conservation exchange"],
    contactPathway: "Via the Indonesian mission in Lisbon",
    contactPerson: "Inês Carvalho, Head of Collections",
    relatedPeopleIds: [],
    relatedContentIds: ["c-sub-museum-profile"],
    collaborationIds: ["pc-pt-maritime"],
    relationshipStatus: "Active",
    lastInteraction: at(-12),
    nextFollowUp: at(4),
    notes: [{ id: "pn-1", kind: "Comment", body: "Interested in a 2027 exhibition slot.", author: "Siti Hapsari", date: at(-12) }],
  },
  {
    id: "pa-example-uni",
    name: "University of Example, Department of Music",
    type: "University",
    country: "United Kingdom",
    city: "London",
    themes: ["Music", "Performing Arts"],
    expertise: ["Ethnomusicology", "Performance research"],
    collaborationInterests: ["Research partnership", "Visiting musicians"],
    contactPathway: "Departmental research office",
    contactPerson: "Dr Helen Okafor",
    relatedPeopleIds: ["pe-2"],
    relatedContentIds: ["c-sub-gamelan"],
    collaborationIds: ["pc-uk-music"],
    institutionSlug: "indonesian-cultural-mission-london",
    relationshipStatus: "Strategic",
    lastInteraction: at(-5),
    nextFollowUp: at(-1),
    notes: [],
  },
  {
    id: "pa-textile-museum",
    name: "Nusantara Textile Museum",
    type: "Museum",
    country: "Indonesia",
    city: "Jakarta",
    themes: ["Craft & Design", "Heritage"],
    expertise: ["Textile conservation", "Collections research"],
    collaborationInterests: ["Touring exhibitions", "Apprenticeship funding"],
    contactPathway: "Partnerships office",
    relatedPeopleIds: ["pe-1"],
    relatedContentIds: ["c-in-textile-museum", "c-sub-textile"],
    collaborationIds: ["pc-sea-textile"],
    institutionSlug: "nusantara-textile-museum",
    relationshipStatus: "Strategic",
    lastInteraction: at(-20),
    notes: [],
  },
  {
    id: "pa-maritime-centre",
    name: "Maritime Knowledge Centre",
    type: "Research Centre",
    country: "Indonesia",
    city: "Makassar",
    themes: ["Heritage", "Indigenous Knowledge"],
    expertise: ["Shipbuilding documentation", "Oral history"],
    collaborationInterests: ["Archival research", "Documentation training"],
    contactPathway: "Director's office",
    relatedPeopleIds: ["pe-c3"],
    relatedContentIds: ["c-in-maritime-centre", "c-sub-maritime"],
    collaborationIds: ["pc-pt-maritime"],
    institutionSlug: "maritime-knowledge-centre",
    relationshipStatus: "Active",
    lastInteraction: at(-8),
    nextFollowUp: at(9),
    notes: [],
  },
  {
    id: "pa-kaliuda",
    name: "Kaliuda Weaving House",
    type: "Community",
    country: "Indonesia",
    city: "Pahunga Lodu",
    themes: ["Craft & Design"],
    expertise: ["Natural dye", "Apprenticeship teaching"],
    collaborationInterests: ["Apprenticeship support", "Hosted visits"],
    contactPathway: "Through the weaving house, not individual weavers",
    relatedPeopleIds: ["pe-1", "pe-c1"],
    relatedContentIds: ["c-sub-sumba-scheduled"],
    collaborationIds: [],
    institutionSlug: "kaliuda-weaving-house",
    relationshipStatus: "Known",
    lastInteraction: at(-30),
    notes: [{ id: "pn-2", kind: "Private note", body: "All approaches go through the weaving house collectively.", author: "Siti Hapsari", date: at(-30) }],
  },
  {
    id: "pa-tokyo-festival",
    name: "Tokyo Screen Forum",
    type: "Festival",
    country: "Japan",
    city: "Tokyo",
    themes: ["Film"],
    expertise: ["Festival programming"],
    collaborationInterests: ["Film exchange", "Director tours"],
    contactPathway: "Programming office",
    relatedPeopleIds: ["pe-3"],
    relatedContentIds: ["c-sub-tokyo-film"],
    collaborationIds: ["pc-jp-film"],
    relationshipStatus: "Active",
    lastInteraction: at(-15),
    notes: [],
  },
  {
    id: "pa-mission-london",
    name: "Indonesian Cultural Mission, London",
    type: "Embassy / Mission",
    country: "United Kingdom",
    city: "London",
    themes: ["Music", "Performing Arts", "Heritage"],
    expertise: ["Programme delivery", "Institutional introductions"],
    collaborationInterests: ["Touring", "Academic partnerships"],
    contactPathway: "Cultural attaché",
    relatedPeopleIds: [],
    relatedContentIds: ["c-in-mission-london"],
    collaborationIds: ["pc-uk-music"],
    institutionSlug: "indonesian-cultural-mission-london",
    relationshipStatus: "Strategic",
    lastInteraction: at(-3),
    notes: [],
  },
  {
    id: "pa-nairobi-centre",
    name: "Nairobi Textile Studio Collective",
    type: "Cultural Centre",
    country: "Kenya",
    city: "Nairobi",
    themes: ["Craft & Design"],
    expertise: ["Natural dye", "Studio practice"],
    collaborationInterests: ["South–south exchange"],
    contactPathway: "Studio coordinator",
    relatedPeopleIds: [],
    relatedContentIds: [],
    collaborationIds: ["pc-sea-textile"],
    relationshipStatus: "New",
    lastInteraction: at(-45),
    notes: [],
  },
];

/* ---------------- inquiries ---------------- */

export const seedInquiries: Inquiry[] = [
  {
    id: "iq-1",
    reference: "IV-2026-0148",
    requesterName: "Dr Helen Okafor",
    requesterRole: "Senior Lecturer in Ethnomusicology",
    organisation: "University of Example",
    country: "United Kingdom",
    email: "h.okafor@example.ac.uk",
    category: "Research & Academic Partnership",
    subject: "Gamelan musicians for a three-year research collaboration",
    summary:
      "We are preparing a funded project on tuning practice and would like to work with Indonesian musicians and an Indonesian research institution as equal partners, not informants.",
    desiredOutcome: "A named institutional partner and two musician collaborators before the funding deadline.",
    timeframe: "Proposal due in ten weeks",
    attachments: ["draft-project-outline.pdf"],
    relatedContentIds: ["c-cf-gamelan", "c-sub-gamelan"],
    receivedAt: at(-9),
    assignedTo: "Siti Hapsari",
    priority: "High",
    status: "Forwarded",
    nextAction: "Confirm the introduction was received",
    qualification: {
      request: "Institutional research partnership plus two musician collaborators.",
      clear: "Yes",
      credible: "Yes",
      culturalArea: "Gamelan, performance research",
      geography: "Indonesia – United Kingdom",
      potentialPartner: "Nusantara Sound Archive; Sekar Bronze Ensemble",
      followUp: "Two weeks after introduction",
      possibleOutcome: "Research partnership",
    },
    clarifications: [
      { id: "cf-1", message: "Could you confirm the funding body and whether partner budget is included?", sentAt: at(-7), sentBy: "Siti Hapsari", response: "Yes — partner budget is 30% of the total, held by the Indonesian partner.", respondedAt: at(-6), status: "Answered" },
    ],
    introductions: [
      { id: "in-1", partnerId: "pa-example-uni", contactPerson: "Dr Helen Okafor", reason: "Existing research relationship with the Sound Archive.", contextShared: "Public profile and prior collaboration summary only.", consentConfirmed: true, introducedAt: at(-3), followUpDate: at(-1), outcome: "" },
    ],
    timeline: [
      { id: "tl-1", date: at(-9), label: "Inquiry received through the public platform", actor: "System", channel: "External" },
      { id: "tl-2", date: at(-8), label: "Reviewed by Siti", actor: "Siti Hapsari", channel: "Internal" },
      { id: "tl-3", date: at(-7), label: "Additional information requested", actor: "Siti Hapsari", channel: "External" },
      { id: "tl-4", date: at(-6), label: "Requester responded", actor: "Dr Helen Okafor", channel: "External" },
      { id: "tl-5", date: at(-4), label: "Institution identified", actor: "Siti Hapsari", channel: "Internal" },
      { id: "tl-6", date: at(-3), label: "Introduction sent", actor: "Siti Hapsari", channel: "External" },
    ],
    notes: [{ id: "iqn-1", kind: "Private note", body: "Funding body has a strict equity requirement — useful leverage for partner budget.", author: "Siti Hapsari", date: at(-6) }],
    collaborationId: "pc-uk-music",
  },
  {
    id: "iq-2",
    reference: "IV-2026-0152",
    requesterName: "Inês Carvalho",
    requesterRole: "Head of Collections",
    organisation: "Museu Nacional de Arte Antiga",
    country: "Portugal",
    email: "ines.carvalho@example.pt",
    category: "Exhibition / Performance",
    subject: "Loan and co-curation for a maritime heritage exhibition",
    summary: "We would like to co-curate a 2027 exhibition on the spice routes with Indonesian institutional partners and Indonesian curatorial authorship.",
    desiredOutcome: "Named co-curator and a loan conversation with a national collection.",
    timeframe: "Planning starts next quarter",
    attachments: [],
    relatedContentIds: ["c-cl-pt-maritime", "c-sub-maritime"],
    receivedAt: at(-5),
    assignedTo: "Siti Hapsari",
    priority: "High",
    status: "Ready to route",
    nextAction: "Introduce the Maritime Knowledge Centre",
    qualification: {
      request: "Exhibition co-curation and loans.",
      clear: "Yes",
      credible: "Yes",
      culturalArea: "Maritime heritage",
      geography: "Indonesia – Portugal",
      potentialPartner: "Maritime Knowledge Centre",
      possibleOutcome: "Exhibition and follow-up programme",
    },
    clarifications: [],
    introductions: [],
    timeline: [
      { id: "tl-7", date: at(-5), label: "Inquiry received", actor: "System", channel: "External" },
      { id: "tl-8", date: at(-4), label: "Qualified by Siti", actor: "Siti Hapsari", channel: "Internal" },
    ],
    notes: [],
    collaborationId: "pc-pt-maritime",
  },
  {
    id: "iq-3",
    reference: "IV-2026-0158",
    requesterName: "Kenji Watanabe",
    requesterRole: "Programme Director",
    organisation: "Tokyo Screen Forum",
    country: "Japan",
    email: "k.watanabe@example.jp",
    category: "Artist / Speaker Invitation",
    subject: "Director invitation for a season of Indonesian cinema",
    summary: "We would like to invite two Indonesian directors for a season with public conversations.",
    desiredOutcome: "Two confirmed directors and travel arrangements.",
    timeframe: "Season opens in three months",
    attachments: [],
    relatedContentIds: ["c-sub-tokyo-film", "c-cf-cinema"],
    receivedAt: at(-2),
    priority: "Normal",
    status: "New",
    nextAction: "Assign an officer",
    qualification: {},
    clarifications: [],
    introductions: [],
    timeline: [{ id: "tl-9", date: at(-2), label: "Inquiry received", actor: "System", channel: "External" }],
    notes: [],
  },
  {
    id: "iq-4",
    reference: "IV-2026-0159",
    requesterName: "Amara Diallo",
    requesterRole: "Features Editor",
    organisation: "Continental Review",
    country: "Kenya",
    email: "a.diallo@example.ke",
    category: "Media & Publication",
    subject: "Interview request on natural dye practice",
    summary: "Looking for an interview with a weaver and permission to reproduce two photographs.",
    desiredOutcome: "One interview and image licensing.",
    timeframe: "Publishing in six weeks",
    attachments: [],
    relatedContentIds: ["c-cf-ikat"],
    receivedAt: at(-1),
    priority: "Normal",
    status: "New",
    nextAction: "Check image rights before responding",
    qualification: {},
    clarifications: [],
    introductions: [],
    timeline: [{ id: "tl-10", date: at(-1), label: "Inquiry received", actor: "System", channel: "External" }],
    notes: [],
  },
  {
    id: "iq-5",
    reference: "IV-2026-0141",
    requesterName: "Marcos Ribeiro",
    requesterRole: "Residency Coordinator",
    organisation: "Porto Material Studio",
    country: "Portugal",
    email: "m.ribeiro@example.pt",
    category: "Cultural Collaboration",
    subject: "Residency places for Indonesian designers",
    summary: "Offering two funded residency places and looking for a route to Indonesian material designers.",
    desiredOutcome: "Applications from Indonesian designers.",
    timeframe: "Open now",
    attachments: [],
    relatedContentIds: ["c-sub-residency"],
    receivedAt: at(-18),
    assignedTo: "Siti Hapsari",
    priority: "Normal",
    status: "In discussion",
    nextAction: "Confirm whether the collaboration request can proceed",
    qualification: { request: "Distribution of a residency call.", clear: "Yes", credible: "Needs checking", culturalArea: "Material design", geography: "Portugal", possibleOutcome: "Repeat exchange" },
    clarifications: [{ id: "cf-2", message: "Could you provide more detail about the proposed dates and host institution?", sentAt: at(-14), sentBy: "Siti Hapsari", response: "Dates confirmed for autumn; host is the studio itself with municipal support.", respondedAt: at(-12), status: "Answered" }],
    introductions: [],
    timeline: [
      { id: "tl-11", date: at(-18), label: "Inquiry received", actor: "System", channel: "External" },
      { id: "tl-12", date: at(-14), label: "Additional information requested", actor: "Siti Hapsari", channel: "External" },
      { id: "tl-13", date: at(-12), label: "Requester responded", actor: "Marcos Ribeiro", channel: "External" },
    ],
    notes: [],
  },
  {
    id: "iq-6",
    reference: "IV-2026-0120",
    requesterName: "Sophie Marchand",
    requesterRole: "Curator",
    organisation: "Institut des Cultures",
    country: "France",
    email: "s.marchand@example.fr",
    category: "Institutional Partnership",
    subject: "Long-term partnership on contemporary performance",
    summary: "Exploring a multi-year partnership with an Indonesian performance institution.",
    desiredOutcome: "A memorandum with one institution.",
    timeframe: "Next year",
    attachments: [],
    relatedContentIds: ["c-cf-performance"],
    receivedAt: at(-40),
    assignedTo: "Siti Hapsari",
    priority: "Low",
    status: "Completed",
    nextAction: "",
    qualification: { request: "Multi-year institutional partnership.", clear: "Yes", credible: "Yes", culturalArea: "Contemporary performance", geography: "France", possibleOutcome: "New institutional relationship" },
    clarifications: [],
    introductions: [{ id: "in-2", partnerId: "pa-mission-london", contactPerson: "Cultural attaché", reason: "Existing programme relationship in Europe.", contextShared: "Public profiles only.", consentConfirmed: true, introducedAt: at(-30), followUpDate: at(-16), outcome: "Meeting held; partnership under discussion at institutional level." }],
    timeline: [
      { id: "tl-14", date: at(-40), label: "Inquiry received", actor: "System", channel: "External" },
      { id: "tl-15", date: at(-30), label: "Introduction sent", actor: "Siti Hapsari", channel: "External" },
      { id: "tl-16", date: at(-16), label: "Follow-up completed", actor: "Siti Hapsari", channel: "Internal" },
    ],
    notes: [],
  },
];

/* ---------------- collaboration pipeline ---------------- */

export const seedPipeline: PipelineCollaboration[] = [
  {
    id: "pc-uk-music",
    title: "Indonesia–UK Music Exchange",
    countries: ["Indonesia", "United Kingdom"],
    themes: ["Music", "Performing Arts"],
    leadOfficer: "Siti Hapsari",
    stage: "Discussion",
    origin: "Public inquiry",
    originTrail: [
      { label: "Story: Bronze and circuit", recordType: "Content", recordId: "c-st-2", date: at(-60) },
      { label: "Inquiry IV-2026-0148", recordType: "Inquiry", recordId: "iq-1", date: at(-9) },
      { label: "Introduction to University of Example", recordType: "Introduction", recordId: "in-1", date: at(-3) },
    ],
    potentialPartnerIds: ["pa-mission-london"],
    confirmedPartnerIds: ["pa-example-uni"],
    objective: "A three-year research partnership on tuning practice with Indonesian co-authorship throughout.",
    context: "Grew out of an inquiry from a UK department after reading the gamelan story.",
    activities: ["Joint funding application", "Two exchange visits", "Public performance in year two"],
    timeline: [
      { period: "Q1", label: "Partner confirmation" },
      { period: "Q2", label: "Proposal submitted" },
    ],
    outputs: [],
    outcomes: [],
    documents: ["draft-project-outline.pdf"],
    inquiryIds: ["iq-1"],
    nextActions: ["Confirm Indonesian partner budget share"],
    publicSlug: "indonesia-uk-music-research",
    contentId: "c-cl-uk-music",
    updatedAt: at(-2),
  },
  {
    id: "pc-pt-maritime",
    title: "Indonesia–Portugal Maritime Heritage",
    countries: ["Indonesia", "Portugal"],
    themes: ["Heritage", "Indigenous Knowledge"],
    leadOfficer: "Siti Hapsari",
    stage: "Ongoing",
    origin: "Existing partner",
    originTrail: [
      { label: "Event encounter at a maritime conference", recordType: "Interaction", date: at(-300) },
      { label: "Institution contact: Maritime Knowledge Centre", recordType: "Partner", recordId: "pa-maritime-centre", date: at(-280) },
      { label: "Inquiry IV-2026-0152", recordType: "Inquiry", recordId: "iq-2", date: at(-5) },
    ],
    potentialPartnerIds: ["pa-mnaa"],
    confirmedPartnerIds: ["pa-maritime-centre"],
    objective: "Shared archival research and a co-curated exhibition on the spice routes.",
    context: "Runs alongside the published collaboration record on the public platform.",
    activities: ["Archive digitisation", "Curatorial exchange", "Exhibition development"],
    timeline: [
      { period: "2026", label: "Archive digitisation" },
      { period: "2027", label: "Exhibition opens in Lisbon" },
    ],
    outputs: [
      { type: "Digital archive", label: "Shared maritime document archive, 1,200 items" },
      { type: "Research paper", label: "Konjo hull proportion study" },
    ],
    outcomes: [{ type: "Research partnership", label: "Ongoing joint research programme between the two centres" }],
    documents: ["mou-2025.pdf"],
    inquiryIds: ["iq-2"],
    nextActions: ["Send the co-curation introduction"],
    publicSlug: "indonesia-portugal-maritime-heritage",
    contentId: "c-cl-pt-maritime",
    updatedAt: at(-4),
  },
  {
    id: "pc-jp-film",
    title: "Indonesia–Japan Film Exchange",
    countries: ["Indonesia", "Japan"],
    themes: ["Film"],
    leadOfficer: "Siti Hapsari",
    stage: "Discussion",
    origin: "Event",
    originTrail: [
      { label: "Event: New Indonesian Cinema", recordType: "Content", recordId: "c-ev-3", date: at(-70) },
      { label: "Inquiry IV-2026-0158", recordType: "Inquiry", recordId: "iq-3", date: at(-2) },
    ],
    potentialPartnerIds: ["pa-tokyo-festival"],
    confirmedPartnerIds: [],
    objective: "A recurring two-way film season with director participation.",
    context: "Second year of contact with the Tokyo programme team.",
    activities: ["Season programming", "Director tour"],
    timeline: [{ period: "Q3", label: "Season in Tokyo" }],
    outputs: [{ type: "Programme", label: "Six-film season" }],
    outcomes: [],
    documents: [],
    inquiryIds: ["iq-3"],
    nextActions: ["Confirm director availability"],
    publicSlug: "indonesia-japan-film-exchange",
    contentId: "c-cl-jp-film",
    updatedAt: at(-2),
  },
  {
    id: "pc-sea-textile",
    title: "Southeast Asian Textile Research Programme",
    countries: ["Indonesia", "Malaysia", "Philippines", "Kenya"],
    themes: ["Craft & Design", "Heritage"],
    leadOfficer: "Siti Hapsari",
    stage: "Ongoing",
    origin: "Research programme",
    originTrail: [{ label: "Research paper on morinda dye chemistry", recordType: "Research", recordId: "rp-2", date: at(-400) }],
    potentialPartnerIds: ["pa-nairobi-centre"],
    confirmedPartnerIds: ["pa-textile-museum"],
    objective: "Comparative dye and technique research across four countries.",
    context: "Published on the public platform; the pipeline record tracks the next phase.",
    activities: ["Field documentation", "Shared dye reference library"],
    timeline: [{ period: "2026", label: "Field documentation" }],
    outputs: [{ type: "Publication", label: "Comparative dye reference" }],
    outcomes: [{ type: "Long-term network", label: "Four-country working group" }],
    documents: [],
    inquiryIds: [],
    nextActions: ["Confirm the Nairobi studio's participation"],
    publicSlug: "southeast-asian-textile-research-programme",
    contentId: "c-cl-sea-textile",
    updatedAt: at(-10),
  },
  {
    id: "pc-porto-design",
    title: "Porto material design exchange",
    countries: ["Indonesia", "Portugal"],
    themes: ["Craft & Design"],
    leadOfficer: "Siti Hapsari",
    stage: "Draft",
    origin: "Public inquiry",
    originTrail: [{ label: "Inquiry IV-2026-0141", recordType: "Inquiry", recordId: "iq-5", date: at(-18) }],
    potentialPartnerIds: ["pa-mnaa"],
    confirmedPartnerIds: [],
    objective: "A repeatable residency route for Indonesian material designers in Portugal.",
    context: "Started from an offer of two residency places.",
    activities: ["Residency listing", "Selection support"],
    timeline: [],
    outputs: [],
    outcomes: [],
    documents: [],
    inquiryIds: ["iq-5"],
    nextActions: ["Verify the residency call before publication"],
    updatedAt: at(-12),
  },
];

/* ---------------- follow-ups, interactions ---------------- */

export const seedFollowUps: FollowUp[] = [
  { id: "fu-1", title: "Check the University of Example introduction was received", dueDate: at(-1), owner: "Siti Hapsari", status: "Open", relatedType: "Inquiry", relatedId: "iq-1", relatedLabel: "IV-2026-0148" },
  { id: "fu-2", title: "Follow up with Museu Nacional de Arte Antiga on the 2027 slot", dueDate: at(-2), owner: "Siti Hapsari", status: "Open", relatedType: "Partner", relatedId: "pa-mnaa", relatedLabel: "Museu Nacional de Arte Antiga" },
  { id: "fu-3", title: "Ask whether the Tokyo programming meeting took place", dueDate: at(0), owner: "Siti Hapsari", status: "Open", relatedType: "Collaboration", relatedId: "pc-jp-film", relatedLabel: "Indonesia–Japan Film Exchange" },
  { id: "fu-4", title: "Review the Porto residency proposal before listing", dueDate: at(3), owner: "Siti Hapsari", status: "Open", relatedType: "Inquiry", relatedId: "iq-5", relatedLabel: "IV-2026-0141" },
  { id: "fu-5", title: "Confirm the Maritime Knowledge Centre co-curation contact", owner: "Siti Hapsari", status: "Open", relatedType: "Partner", relatedId: "pa-maritime-centre", relatedLabel: "Maritime Knowledge Centre" },
  { id: "fu-6", title: "Send the Institut des Cultures meeting summary", dueDate: at(-16), owner: "Siti Hapsari", status: "Completed", relatedType: "Inquiry", relatedId: "iq-6", relatedLabel: "IV-2026-0120", completedAt: at(-16) },
];

export const seedInteractions: Interaction[] = [
  { id: "ix-1", kind: "Introduction", date: at(-3), participants: "Siti Hapsari, Dr Helen Okafor, Nusantara Sound Archive", partnerId: "pa-example-uni", inquiryId: "iq-1", collaborationId: "pc-uk-music", summary: "Introduction sent with consent from both sides.", nextAction: "Follow up in two weeks", recordedBy: "Siti Hapsari" },
  { id: "ix-2", kind: "Meeting", date: at(-12), participants: "Siti Hapsari, Inês Carvalho", partnerId: "pa-mnaa", collaborationId: "pc-pt-maritime", summary: "Discussed a 2027 exhibition slot and Indonesian curatorial authorship.", nextAction: "Introduce the Maritime Knowledge Centre", privateNote: "Budget for loans is not yet secured on their side.", recordedBy: "Siti Hapsari" },
  { id: "ix-3", kind: "Event encounter", date: at(-15), participants: "Siti Hapsari, Kenji Watanabe", partnerId: "pa-tokyo-festival", collaborationId: "pc-jp-film", summary: "Met at a regional festival; renewed interest in a two-way season.", recordedBy: "Siti Hapsari" },
  { id: "ix-4", kind: "Email", date: at(-8), participants: "Siti Hapsari, Maritime Knowledge Centre", partnerId: "pa-maritime-centre", summary: "Shared the Portuguese exhibition brief for comment.", recordedBy: "Siti Hapsari" },
];

/* ---------------- taxonomy, curation ---------------- */

const themeTerms = [
  "Heritage", "Performing Arts", "Music", "Craft & Design", "Film", "Contemporary Culture",
  "Culinary Culture", "Indigenous Knowledge", "Architecture",
];

export const seedTaxonomy: TaxonomyTerm[] = [
  ...themeTerms.map((label, i) => ({ id: `tx-th-${i}`, category: "Theme" as const, label, usage: 3 + ((i * 5) % 17) })),
  ...["Java", "Sumba", "Sulawesi", "Maluku", "Kalimantan", "Bali"].map((label, i) => ({ id: `tx-geo-${i}`, category: "Geography" as const, label, usage: 2 + i * 2 })),
  ...["Textile", "Ensemble music", "Boatbuilding", "Screen culture", "Foodways"].map((label, i) => ({ id: `tx-cc-${i}`, category: "Cultural Category" as const, label, usage: 4 + i })),
  ...["Europe", "East Asia", "Southeast Asia", "Africa", "Americas", "Oceania"].map((label, i) => ({ id: `tx-gr-${i}`, category: "Global Region" as const, label, usage: 1 + i * 3 })),
  ...["Indonesia", "United Kingdom", "Japan", "Portugal", "Kenya", "Brazil", "Australia", "Germany", "United States"].map((label, i) => ({ id: `tx-co-${i}`, category: "Country" as const, label, usage: 1 + ((i * 4) % 11) })),
  ...["Learn", "Visit", "Collaborate", "Research", "Report"].map((label, i) => ({ id: `tx-ui-${i}`, category: "User Intent" as const, label, usage: 2 + i })),
  ...["UNESCO Intangible Cultural Heritage", "World Heritage Site", "National Cultural Heritage"].map((label, i) => ({ id: `tx-rec-${i}`, category: "Recognition" as const, label, usage: 1 + i })),
  ...["Exhibition", "Performance", "Screening season", "Open studio", "Symposium", "Festival"].map((label, i) => ({ id: `tx-et-${i}`, category: "Event Type" as const, label, usage: 1 + i })),
  ...["Research", "Exhibition", "Performance exchange", "Training"].map((label, i) => ({ id: `tx-ct-${i}`, category: "Collaboration Type" as const, label, usage: 1 + i })),
];

export const seedCuration: CurationSlot[] = [
  { id: "cu-1", section: "Hero", contentId: "c-st-1", label: "Two years in a single cloth", order: 0 },
  { id: "cu-2", section: "In Focus", contentId: "c-ev-1", label: "Warp & Weft: Two Years in a Cloth", order: 0 },
  { id: "cu-3", section: "In Focus", contentId: "c-sub-sumba-scheduled", label: "Sumba Weaving Week open studios", order: 1 },
  { id: "cu-4", section: "Featured Collection", contentId: "c-co-1", label: "Made slowly", order: 0 },
  { id: "cu-5", section: "People & Organisations", contentId: "c-pe-1", label: "Rambu Ana Hàmu", order: 0 },
  { id: "cu-6", section: "People & Organisations", contentId: "c-pe-2", label: "Dimas Prayoga", order: 1 },
  { id: "cu-7", section: "Coming Up", contentId: "c-ev-3", label: "New Indonesian Cinema", order: 0 },
  { id: "cu-8", section: "Collaborations", contentId: "c-cl-uk-music", label: "Indonesia–UK Music Research Collaboration", order: 0 },
];

export const seedFocusOverrides: FocusOverride[] = [
  { contentId: "c-sub-sumba-scheduled", label: "Sumba Weaving Week open studios", mode: "Featured happening", until: at(20) },
  { contentId: "c-ev-6", label: "Material Futures", mode: "Editorial priority" },
];

/* ---------------- activity and notifications ---------------- */

export const seedActivity: ActivityEntry[] = [
  { id: "ac-1", date: at(0, 9), actor: "Maya Rahardjo", action: "approved", recordType: "Content", recordId: "c-sub-gamelan", recordTitle: "Gamelan Across Oceans" },
  { id: "ac-2", date: at(0, 9), actor: "Tomás Ferreira", action: "confirmed media rights for 6 photographs", recordType: "Media", recordId: "c-sub-batik-media", recordTitle: "Batik pesisir" },
  { id: "ac-3", date: at(-1, 15), actor: "Siti Hapsari", action: "routed a research inquiry to an institution", recordType: "Inquiry", recordId: "iq-1", recordTitle: "IV-2026-0148" },
  { id: "ac-4", date: at(-1, 11), actor: "Rui Tavares", action: "returned a revision", recordType: "Content", recordId: "c-sub-textile", recordTitle: "Living Textile Traditions" },
  { id: "ac-5", date: at(-2, 16), actor: "Nur Aisyah", action: "verified a source", recordType: "Source", recordId: "src-3", recordTitle: "Proportional rule systems in Konjo hull construction" },
  { id: "ac-6", date: at(-2, 10), actor: "Wayan Sudarma", action: "recorded a cultural review decision", recordType: "Content", recordId: "c-sub-maritime", recordTitle: "Reading the Sea", sensitive: true },
  { id: "ac-7", date: at(-3, 14), actor: "Maya Rahardjo", action: "scheduled publication", recordType: "Content", recordId: "c-sub-sumba-scheduled", recordTitle: "Sumba Weaving Week open studios" },
  { id: "ac-8", date: at(-4, 12), actor: "Siti Hapsari", action: "created an introduction", recordType: "Inquiry", recordId: "iq-6", recordTitle: "IV-2026-0120" },
];

export const seedNotifications: AdminNotification[] = [
  { id: "an-1", title: "Ready for your approval", body: "“Gamelan Across Oceans” has cleared all required stages.", date: at(-1, 17), read: false, roles: ["Managing Editor", "Super Admin"], href: { type: "content", id: "c-sub-gamelan" } },
  { id: "an-2", title: "Verification needed", body: "Two claims on “Reading the Sea” still need sources.", date: at(-2, 9), read: false, roles: ["Researcher / Fact Checker", "Super Admin"], href: { type: "content", id: "c-sub-maritime" } },
  { id: "an-3", title: "Rights issue", body: "“Batik pesisir” has an image without a model release.", date: at(-2, 14), read: false, roles: ["Multimedia Editor", "Managing Editor", "Super Admin"], href: { type: "content", id: "c-sub-batik-media" } },
  { id: "an-4", title: "Inquiry assigned", body: "IV-2026-0152 is ready to route to a partner.", date: at(-3, 10), read: true, roles: ["Partnership Officer", "Super Admin"], href: { type: "inquiry", id: "iq-2" } },
  { id: "an-5", title: "Follow-up due", body: "Two partnership follow-ups are overdue.", date: at(-1, 8), read: false, roles: ["Partnership Officer", "Super Admin"] },
  { id: "an-6", title: "Language review requested", body: "“Contemporary Indonesian Cinema” is waiting for English editing.", date: at(-3, 11), read: false, roles: ["English Editor", "Super Admin"], href: { type: "content", id: "c-sub-cinema-subject" } },
  { id: "an-7", title: "Subject review requested", body: "“Reading the Sea” is assigned to you for cultural review.", date: at(-5, 9), read: false, roles: ["Subject Reviewer", "Super Admin"], href: { type: "content", id: "c-sub-maritime" } },
];

export const researchResources = papers;
